AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: covid19-twitter-bot

Globals:
  Function:
    Timeout: 100

Resources:
 tweetIrishCovid19Stats:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: index.handler
      Runtime: nodejs12.x
